codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90..100"
  status:
    project:
      diff_coverage:
        target: 90%
      default:
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
